name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user/problem does this solve?
      placeholder: What is currently hard or impossible?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the change you want to see.
      placeholder: Describe behavior, API shape, and UX expectations.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Links, mockups, references, or related issues.
